#ifndef __K4A_MKV2IMAGE_VERSION__
#define __K4A_MKV2IMAGE_VERSION__

#define TO_STRING_EXP(v) #v
#define TO_STRING(v)     TO_STRING_EXP(v)

#define K4A_MKV2IMAGE_VERSION_MAJOR    0
#define K4A_MKV2IMAGE_VERSION_MINOR    1
#define K4A_MKV2IMAGE_VERSION_REVISION 0

#define K4A_MKV2IMAGE_VERSION TO_STRING( K4A_MKV2IMAGE_VERSION_MAJOR ) "." TO_STRING( K4A_MKV2IMAGE_VERSION_MINOR ) "." TO_STRING( K4A_MKV2IMAGE_VERSION_REVISION )

#endif // __K4A_MKV2IMAGE_VERSION__